#!/usr/bin/env python3
"""Generate the synthetic benchmark design (SystemVerilog, stdlib only).

Design: N registers of W bits in S leaf modules (bench_leaf) under bench_top.
Each register is an XNOR Fibonacci LFSR. It advances only when its enable is
set. The enable comes from a per-leaf 32-bit LFSR: a register is enabled when
an 8-bit slice of that LFSR is below `thresh` (so P(enable) = thresh / 256).
That sets the toggle density rho = thresh / 256.

One segment: pulse `start` for one clock (E0, the registers load a value
derived from `seed`), run `seg_len` clocks (E1..EL), `done` goes high after
EL. `done` stays high until the next `start`. All three testbenches use the
same schedule: 4 reset edges, then E0..E(L+1) per segment with one idle edge
between segments (L+3 edges per segment), and `aux_i` tied to 0.

Files written:
  bench_dut.sv   bench_leaf, bench_top (the design)
  bench_wrap.sv  bench_wrap (variant b: HDL clock, reset, segment control)
  bench_tb.sv    bench_tb   (variant c: pure SystemVerilog testbench)
"""
import argparse
import os

# XNOR LFSR taps (Xilinx XAPP052), 1-based bit positions.
TAPS = {
    4: (4, 3), 8: (8, 6, 5, 4), 12: (12, 6, 4, 1), 16: (16, 15, 13, 4),
    24: (24, 23, 22, 17), 32: (32, 22, 2, 1), 48: (48, 47, 21, 20),
    64: (64, 63, 61, 60), 128: (128, 126, 101, 99),
}
NPROBE = 16  # probe_i outputs and aux_i inputs of bench_top (used by cocotb "touches")


def feedback(var, w):
    taps = " ^ ".join(f"{var}[{t - 1}]" for t in TAPS[w])
    return f"~({taps})"


def split_regs(n, s):
    """Registers per leaf: as even as possible."""
    base, extra = divmod(n, s)
    return [base + (1 if i < extra else 0) for i in range(s)]


def n_signals(n, w, s):
    """Approximate number of trace handles (unique FST/VCD ids) for the full trace.

    Fitted from VCD dumps of three sizes (see README): about 4 per register
    (data, enable, feedback, init) plus a small constant.
    """
    return 4 * n + 40


def dut_sv(n, w, s):
    assert w in TAPS, f"W must be one of {sorted(TAPS)}"
    assert 1 <= s <= n
    out = []
    out.append("// generated by gen_design.py: do not edit")
    out.append("`timescale 1ns/1ps")
    out.append("module bench_leaf #(parameter int NREG = 1, parameter int W = 8, parameter int LEAF = 0) (")
    out.append("  input  logic clk, load, run,")
    out.append("  input  logic [31:0] seed,")
    out.append("  input  logic [8:0]  thresh,")
    out.append("  output logic [31:0] probe")
    out.append(");")
    out.append("  localparam int NW = (W + 31) / 32;")
    out.append("  logic [31:0] elfsr;")
    out.append(f"  wire elfsr_fb = {feedback('elfsr', 32)};")
    out.append("  always_ff @(posedge clk) begin")
    out.append("    if (load) elfsr <= seed ^ (32'(LEAF) * 32'h85EBCA6B) ^ 32'h1;")
    out.append("    else if (run) elfsr <= {elfsr[30:0], elfsr_fb};")
    out.append("  end")
    out.append("  logic [W-1:0] d_first;")
    out.append("  for (genvar i = 0; i < NREG; i++) begin : g")
    out.append("    logic [W-1:0] d;")
    out.append("    localparam int OFF = (i * 5) % 24;")
    out.append("    wire en = ({1'b0, elfsr[OFF +: 8]} < thresh);")
    out.append("    wire [32*NW-1:0] ini = {NW{seed ^ (32'(LEAF * 65536 + i) * 32'h9E3779B1)}};")
    out.append(f"    wire fb = {feedback('d', w)};")
    out.append("    always_ff @(posedge clk) begin")
    out.append("      if (load) d <= ini[W-1:0] & ~W'(1);")
    out.append("      else if (run && en) d <= {d[W-2:0], fb};")
    out.append("    end")
    out.append("  end")
    out.append("  assign d_first = g[0].d;")
    out.append("  assign probe = 32'(d_first);")
    out.append("endmodule")
    out.append("")
    ports = ["  input  logic clk, rst_n, start,",
             "  input  logic [31:0] seed, seg_len,",
             "  input  logic [8:0]  thresh,",
             "  output logic done,"]
    ports += [f"  output logic [31:0] probe_{i}," for i in range(NPROBE)]
    ports += [f"  input  logic [31:0] aux_{i}," for i in range(NPROBE - 1)]
    ports += [f"  input  logic [31:0] aux_{NPROBE - 1}"]
    out.append("module bench_top (")
    out += ports
    out.append(");")
    out.append("  logic running;")
    out.append("  logic [31:0] cnt;")
    out.append("  wire load = start & ~running;")
    out.append("  always_ff @(posedge clk) begin")
    out.append("    if (!rst_n) begin running <= 1'b0; done <= 1'b0; cnt <= 32'd0; end")
    out.append("    else if (load) begin running <= 1'b1; done <= 1'b0; cnt <= 32'd0; end")
    out.append("    else if (running) begin")
    out.append("      if (cnt == seg_len - 32'd1) begin running <= 1'b0; done <= 1'b1; end")
    out.append("      else cnt <= cnt + 32'd1;")
    out.append("    end")
    out.append("  end")
    out.append(f"  logic [31:0] lp [{s}];")
    for i, nreg in enumerate(split_regs(n, s)):
        out.append(f"  bench_leaf #(.NREG({nreg}), .W({w}), .LEAF({i})) u_leaf{i} "
                   f"(.clk(clk), .load(load), .run(running), .seed(seed), .thresh(thresh), .probe(lp[{i}]));")
    for i in range(NPROBE):
        out.append(f"  assign probe_{i} = lp[{i % s}];")
    out.append("endmodule")
    return "\n".join(out) + "\n"


def dut_inst(prefix):
    """Instance of bench_top with ports connected to signals named like the ports."""
    lines = ["  // verilator tracing_on",
             "  bench_top dut (.clk(clk), .rst_n(rst_n), .start(start), .seed(seed), .seg_len(seg_len),",
             "    .thresh(thresh), .done(done),"]
    lines += [f"    .probe_{i}(probe_{i})," for i in range(NPROBE)]
    lines += [f"    .aux_{i}(32'd0)," for i in range(NPROBE - 1)]
    lines += [f"    .aux_{NPROBE - 1}(32'd0));", "  // verilator tracing_off"]
    return "\n".join(lines)


def wrap_sv():
    o = ["// generated by gen_design.py: do not edit",
         "`timescale 1ns/1ps",
         "// Variant b: the wrapper drives clock, reset, and segment control.",
         "// Software writes seed_in and increments req. The wrapper runs one segment per request",
         "// and pulses seg_done.",
         "module bench_wrap ( // verilator tracing_off",
         "  input  logic [31:0] seed_in, seg_len,",
         "  input  logic [8:0]  thresh,",
         "  input  logic [31:0] req,",
         "  output logic seg_done,",
         "  output logic [63:0] cyc,",
         "  output logic [31:0] chk",
         ");",
         "  logic clk = 1'b0;",
         "  always #5 clk = ~clk;",
         "  logic rst_n = 1'b0, start = 1'b0, done;",
         "  logic [31:0] seed = 32'd0, ack = 32'd0;",
         "  logic [31:0] " + ", ".join(f"probe_{i}" for i in range(NPROBE)) + ";",
         dut_inst("dut"),
         "  typedef enum logic [2:0] {S_RST, S_IDLE, S_START, S_RUN} st_t;",
         "  st_t st = S_RST;",
         "  logic [2:0] rcnt = 3'd0;",
         "  initial begin cyc = 64'd0; chk = 32'd0; seg_done = 1'b0; end",
         "  always_ff @(posedge clk) begin",
         "    cyc <= cyc + 64'd1;",
         "    seg_done <= 1'b0;",
         "    start <= 1'b0;",
         "    case (st)",
         "      S_RST: if (rcnt == 3'd3) begin",
         "        rst_n <= 1'b1;",
         "        if (req != ack) begin ack <= req; seed <= seed_in; start <= 1'b1; st <= S_START; end",
         "        else st <= S_IDLE;",
         "      end else rcnt <= rcnt + 3'd1;",
         "      S_IDLE: if (req != ack) begin ack <= req; seed <= seed_in; start <= 1'b1; st <= S_START; end",
         "      S_START: st <= S_RUN;",
         "      S_RUN: if (done) begin chk <= chk * 32'd31 + probe_0; seg_done <= 1'b1; st <= S_IDLE; end",
         "      default: st <= S_IDLE;",
         "    endcase",
         "  end",
         "endmodule"]
    return "\n".join(o) + "\n"


def tb_sv():
    o = ["// generated by gen_design.py: do not edit",
         "`timescale 1ns/1ps",
         "// Variant c: pure SystemVerilog testbench. Plusargs: +L= +SEGS= +THRESH= [+trace]",
         "module bench_tb;",
         "  // verilator tracing_off",
         "  logic clk = 1'b0;",
         "  always #5 clk = ~clk;",
         "  logic rst_n = 1'b0, start = 1'b0, done;",
         "  logic [31:0] seed = 32'd0, seg_len = 32'd1000;",
         "  logic [8:0] thresh = 9'd128;",
         "  logic [31:0] " + ", ".join(f"probe_{i}" for i in range(NPROBE)) + ";",
         dut_inst("dut"),
         "  longint unsigned cyc = 0;",
         "  always @(posedge clk) cyc <= cyc + 1;",
         "  int L, segs, th;",
         "  logic [31:0] chk = 32'd0;",
         "  initial begin",
         "    if (!$value$plusargs(\"L=%d\", L)) L = 1000;",
         "    if (!$value$plusargs(\"SEGS=%d\", segs)) segs = 100;",
         "    if (!$value$plusargs(\"THRESH=%d\", th)) th = 128;",
         "    seg_len = 32'(L);",
         "    thresh = 9'(th);",
         "    if ($test$plusargs(\"trace\")) begin",
         "      $dumpfile(\"trace.fst\");",
         "      $dumpvars;",
         "    end",
         "    repeat (4) @(posedge clk);",
         "    rst_n <= 1'b1;",
         "    for (int s = 0; s < segs; s++) begin",
         "      if (s > 0) @(posedge clk);  // idle edge between segments (as in variants a and b)",
         "      seed <= 32'(s + 1) * 32'h9E3779B1;",
         "      start <= 1'b1;",
         "      @(posedge clk);",
         "      start <= 1'b0;",
         "      repeat (L) @(posedge clk);",
         "      @(posedge clk);",
         "      if (!done) $fatal(1, \"done not set\");",
         "      chk = chk * 32'd31 + probe_0;",
         "    end",
         "    #1;  // let the last edge's nonblocking updates settle before the count is read",
         "    $display(\"BENCH cycles=%0d chk=%0d\", cyc, chk);",
         "    $finish;",
         "  end",
         "endmodule"]
    return "\n".join(o) + "\n"


def write_design(n, w, s, outdir):
    os.makedirs(outdir, exist_ok=True)
    for name, text in (("bench_dut.sv", dut_sv(n, w, s)), ("bench_wrap.sv", wrap_sv()), ("bench_tb.sv", tb_sv())):
        with open(os.path.join(outdir, name), "w") as f:
            f.write(text)
    return outdir


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--regs", type=int, required=True, help="N: number of registers")
    ap.add_argument("--width", type=int, required=True, help="W: bits per register (%s)" % sorted(TAPS))
    ap.add_argument("--subs", type=int, default=1, help="S: number of sub-modules")
    ap.add_argument("--outdir", required=True)
    a = ap.parse_args()
    write_design(a.regs, a.width, a.subs, a.outdir)


if __name__ == "__main__":
    main()
